### PR TITLE
use `wheel` event instead of `mousewheel` (fixes #69)

### LINKED ISSUE #69: Mousewheel does not work on Firefox
The event [used to modify the distance](https://github.com/aframevr-userland/aframe-cli/blob/master/templates/aframe-360-tour-template/app/js/components/helper.js#L42) through the mouse wheel is [non-standard](https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel) and only works in Chrome. The standard event is [`wheel`](https://developer.mozilla.org/en-US/docs/Web/Events/wheel).

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

File: templates/aframe-360-tour-template/app/js/components/helper.js [hunk 1]
```diff
@@ -25,46 +25,46 @@ AFRAME.registerComponent('hotspot-helper', {
...
+    // Copy position to clipboard.
     var copyPosition = uiContainer.querySelector('#hh-copy-position');
     copyPosition.addEventListener('click', function () {
       self.copyToClipboard(self.position);
     });
 
-    // mousewheel distance
-    document.body.addEventListener('mousewheel', this.handleMouseWheel.bind(this));
+    // Mouse-wheel distance.
+    window.addEventListener('wheel', this.handleMouseWheel.bind(this));
```
Comment (cvan) [inline templates/aframe-360-tour-template/app/js/components/helper.js]: changed this

**Comment by cvan** [comment]
r+

**Comment by caseyyee** [comment]
Thanks for this!
